apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: app.ewang.com
  namespace: default
spec:
  secretName: app-ewang
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: ewang.com
  organization:
  - CA
  dnsNames:
  - ewang.com
  - app.ewang.com
