apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hulixue-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tom-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 500
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 200
